name: Publish Website of Rails
on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: demo-ruby-panel.server18.arhamsoft.info
        username: ftp_deploy@demo-ruby-panel.server18.arhamsoft.info
        password: "~zdDy5VWmytd"
        dry-run: false
        # exclude: |
        #   **/.git*
        #   **/.git*/**
        #   **/assets/home/*
        #   **/assets/site/*
        #   **/system*
        #   **/system*/**
        #   **/uploads*
        #   **/uploads*/**
        #   **/phpmyadmin*
        #   **/phpmyadmin*/**
        #   **/node_modules/**